      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4)
	 
	   PARAMETER (ZERO = 0.0D0, ONE = 1.0D0, TWO = 2.0D0)
	 
	   E1=PROPS(1) ! MODULUS IN THE LONGITUDINAL DIRECTION
	   E2=PROPS(2) ! MODULUS IN THE TRANSVERSE DIRECTION
	   E3=PROPS(3)
	   NU12 = PROPS(4)
	   NU13 = PROPS(5)
	   NU23 = PROPS(6)
	   G12 = PROPS(7)
	   G13 = PROPS(8)
	   G23 = PROPS(9)
	   
	   XT = PROPS(10)
	   XC = PROPS(11)
	   YT = PROPS(12)
	   YC = PROPS(13)
	   SL = PROPS(14)
	   ST = PROPS(15)
	   
	   NU21 = (E2/E1)*NU12
	   NU31 = (E3/E1)*NU13
	   NU32 = (E3/E2)*NU23
	   
	   TERM = ONE/(ONE - NU12*NU21 - NU23*NU32 - NU13*NU31 - TWO*NU21*NU32*NU13)
	   STATEV = 0
	   
	   
	   DO i = 1, NTENS
	   DO j = 1, NTENS
	   DDSDDE(i,j)= ZERO
	   END DO
	   END DO
	   
	   DDSDDE(1,1) = E1*(ONE-NU23*NU32)*TERM
	   DDSDDE(2,2) = E2*(ONE-NU13*NU31)*TERM
	   DDSDDE(3,3) = E3*(ONE-NU12*NU21)*TERM
	   DDSDDE(1,2) = E1*(NU21+NU31*NU23)*TERM
	   DDSDDE(2,1) = E2*(NU12+NU32*NU13)*TERM
	   DDSDDE(1,3) = E1*(NU31+NU21*NU32)*TERM
	   DDSDDE(3,1) = E3*(NU13+NU12*NU23)*TERM
	   DDSDDE(2,3) = E2*(NU32+NU12*NU31)*TERM
	   DDSDDE(3,2) = E3*(NU23+NU21*NU13)*TERM
	   DDSDDE(4,4) = G12
	   DDSDDE(5,5) = G13
	   DDSDDE(6,6) = G23
	   
	   
	   DO i=1, NTENS
       DO j=1, NTENS
	   STRESS(j)=STRESS(j)+DDSDDE(j, i)*DSTRAN(i)
       END DO
       END DO
	   
	   IF ( STRESS(1) .GE. ZERO ) THEN
	   STATEV(1) = (STRESS(1)/XT)**2 + (STRESS(6)**2 + STRESS(5)**2)/(SL**2)
	   STATEV(2) = ZERO
	   ELSE
	   STATEV(1) = ZERO
	   STATEV(2) = (-STRESS(1)/XC)
	   END IF
	   
	   
	   IF ( STRESS(2) + STRESS(3) .GE. ZERO ) THEN
	   STATEV(3) = (ONE/(YT)**2) * (STRESS(2) + STRESS(3))**2 + (ONE/(ST)**2) * (STRESS(4)**2 - STRESS(2)*STRESS(3)) + (ONE/(SL)**2) * (STRESS(5)**2 + STRESS(6)**2)
	   STATEV(4) = ZERO
	   ELSE
	   STATEV(3) = ZERO
	   STATEV(4) = (ONE/(TWO*YT)**2) * (STRESS(2) + STRESS(3))**2 + (ONE/(ST)**2) * (STRESS(4)**2 - STRESS(2)*STRESS(3)) + (ONE/(SL)**2) * (STRESS(5)**2 + STRESS(6)**2) + (ONE/YC)*((YC/(TWO*ST))**2 - ONE) * (STRESS(2) + STRESS(3)) 
	   END IF
	   
	  RETURN
      END
